INSERT INTO categoria (nome) values ('Dever de casa');
INSERT INTO categoria (nome) values ('Estudar para prova');
INSERT INTO categoria (nome) values ('Pesquisa bibliográfica');
INSERT INTO categoria (nome) values ('Trabalho em grupo');
INSERT INTO categoria (nome) values ('Participar de evento acadêmico');
INSERT INTO categoria (nome) values ('Preparar apresentação');

INSERT INTO usuario (nome, ativo) values ('Pedro', true);
insert into usuario (nome, ativo) values ('Agnes Perrin', true);
insert into usuario (nome, ativo) values ('Ruthann Palumbo', false);
insert into usuario (nome, ativo) values ('Willabella Cronkshaw', true);
insert into usuario (nome, ativo) values ('Malissa MacElroy', true);
insert into usuario (nome, ativo) values ('Schuyler Upward', false);
insert into usuario (nome, ativo) values ('Armstrong MacConnel', true);
insert into usuario (nome, ativo) values ('Mendy Dragon', false);
insert into usuario (nome, ativo) values ('Web Coulson', true);
insert into usuario (nome, ativo) values ('Mic Essex', false);
insert into usuario (nome, ativo) values ('Berty Lippett', false);
insert into usuario (nome, ativo) values ('Gottfried Rickard', true);
insert into usuario (nome, ativo) values ('Cornall Berryann', true);
insert into usuario (nome, ativo) values ('Nolan Doidge', true);
insert into usuario (nome, ativo) values ('Miguela Staining', true);
insert into usuario (nome, ativo) values ('Estevan Winkett', false);
insert into usuario (nome, ativo) values ('Felicle Dubarry', false);
insert into usuario (nome, ativo) values ('Yasmin Peacher', true);
insert into usuario (nome, ativo) values ('Maurizia Fitton', false);
insert into usuario (nome, ativo) values ('Daloris Badgers', true);
insert into usuario (nome, ativo) values ('Ernst Winslade', true);
insert into usuario (nome, ativo) values ('Francoise Skipp', false);
insert into usuario (nome, ativo) values ('Wayland MacIntosh', false);
insert into usuario (nome, ativo) values ('Maisey Flewan', false);
insert into usuario (nome, ativo) values ('Jaclyn Sarfas', true);
insert into usuario (nome, ativo) values ('Kaitlyn Ensley', true);
insert into usuario (nome, ativo) values ('Caresa Alekseicik', true);
insert into usuario (nome, ativo) values ('Zora Simester', true);
insert into usuario (nome, ativo) values ('Agosto Lang', true);
insert into usuario (nome, ativo) values ('Arielle Bradnam', true);
insert into usuario (nome, ativo) values ('Patricio Kirsopp', true);
insert into usuario (nome, ativo) values ('Brennan Cawthorn', true);
insert into usuario (nome, ativo) values ('Olly Demann', false);
insert into usuario (nome, ativo) values ('Rich Feckey', true);
insert into usuario (nome, ativo) values ('Chev Aimson', true);
insert into usuario (nome, ativo) values ('Robin Febre', true);
insert into usuario (nome, ativo) values ('Valentina Smitherham', false);
insert into usuario (nome, ativo) values ('Nessy Neal', false);
insert into usuario (nome, ativo) values ('Dyann Nelius', true);
insert into usuario (nome, ativo) values ('Lind Persehouse', true);
insert into usuario (nome, ativo) values ('Vitia Mercey', true);
insert into usuario (nome, ativo) values ('Phylis Curro', true);
insert into usuario (nome, ativo) values ('Tabina Busst', false);
insert into usuario (nome, ativo) values ('Avrit De Luna', true);
insert into usuario (nome, ativo) values ('Viva Traher', true);
insert into usuario (nome, ativo) values ('Kittie Reams', false);
insert into usuario (nome, ativo) values ('Laryssa Mortel', true);
insert into usuario (nome, ativo) values ('Bailey Terese', true);
insert into usuario (nome, ativo) values ('Jean Whall', false);
insert into usuario (nome, ativo) values ('Yuri Stogill', true);
insert into usuario (nome, ativo) values ('Arney Willgoose', false);

INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Tarefa de matemática', '2023-04-01', null, 'Exercícios do capítulo 3', 'PENDENTE', 1, 1);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Exercícios de Português', '2023-04-10', null, null, 'PENDENTE', 1, 2);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Resenha do livro "Vidas Secas"', '2023-04-05', '2023-04-02', 'Ler até o capítulo 5', 'ENTREGUE', 3, 4);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Apresentação de slides sobre física', '2023-04-12', null, '10 minutos de duração', 'PENDENTE', 6, 6);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho sobre a Revolução Francesa', '2023-04-20', '2023-04-15', 'Conferir as referências bibliográficas', 'ENTREGUE', 3, 8);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Lista de exercícios de Química', '2023-04-09', null, 'Fazer os exercícios do capítulo 4', 'PENDENTE', 1, 10);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para a prova de História', '2023-04-19', null, 'Revisar os resumos dos capítulos', 'PENDENTE', 2, 13);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Participação em evento científico', '2023-04-23', '2023-04-23', 'Apresentação de pôster', 'ENTREGUE', 5, 17);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho em grupo de Biologia', '2023-04-08', null, 'Realizar as pesquisas em conjunto', 'PENDENTE', 4, 21);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparação para apresentação oral', '2023-04-22', '2023-04-20', 'Treinar a dicção', 'ENTREGUE', 6, 27);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Dever de casa de Matemática', '2023-04-11', null, 'Exercícios do capítulo 2', 'PENDENTE', 1, 30);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Revisar capítulo 2', '2023-04-05', null, 'Revisão da matéria antes da prova', 'PENDENTE', 2, 10);

INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Pesquisa sobre o Renascimento', '2023-04-08', null, 'Trabalho de História', 'PENDENTE', 3, 20);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho sobre sustentabilidade', '2023-04-10', null, null, 'PENDENTE', 4, 30);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Participação em congresso de engenharia', '2023-04-15', '2023-04-12', 'Palestra sobre desenvolvimento sustentável', 'ENTREGUE', 5, 40);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparar slides para apresentação de marketing', '2023-04-18', null, 'Apresentação em grupo', 'PENDENTE', 6, 5);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Exercícios de física', '2023-04-20', null, 'Lista de exercícios', 'PENDENTE', 1, 15);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de inglês', '2023-04-22', null, 'Revisão da gramática', 'PENDENTE', 2, 25);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Pesquisa sobre a história da arte', '2023-04-25', null, null, 'PENDENTE', 3, 35);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho em grupo de biologia', '2023-04-30', null, 'Pesquisa sobre genética', 'PENDENTE', 4, 45);

INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparar slides para apresentação sobre História', '2023-04-10', null, 'Utilizar imagens ilustrativas', 'PENDENTE', 6, 17);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de Física', '2023-04-15', null, null, 'PENDENTE', 2, 22);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Fazer resenha do livro "Vidas Secas"', '2023-04-05', null, 'Ler até o capítulo 7', 'PENDENTE', 3, 11);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Realizar exercícios de Biologia', '2023-04-12', null, 'Do capítulo 5 ao 8', 'PENDENTE', 1, 38);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Fazer trabalho em grupo de Química', '2023-04-20', null, 'Apresentação em slides', 'PENDENTE', 4, 6);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Participar de congresso sobre Direito', '2023-04-30', '2023-04-28', 'Levar currículo', 'ENTREGUE', 5, 27);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparar apresentação sobre os Maias', '2023-04-07', null, 'Incluir informações sobre o contexto histórico', 'PENDENTE', 6, 45);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Realizar pesquisa sobre o aquecimento global', '2023-04-18', null, 'Utilizar gráficos para ilustrar dados', 'PENDENTE', 3, 29);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de Matemática', '2023-04-25', null, null, 'PENDENTE', 2, 2);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Participação em congresso', '2023-05-15', null, 'Inscrição e preparação de pôster', 'PENDENTE', 5, 18);

INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Lista de exercícios de química', '2023-04-05', null, null, 'PENDENTE', 1, 7);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de história', '2023-04-10', null, 'Capítulos 5 e 6 do livro didático', 'PENDENTE', 2, 12);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Leitura complementar sobre filosofia', '2023-04-20', null, 'Artigo sobre pensamento de Sócrates', 'PENDENTE', 3, 30);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho em grupo de biologia', '2023-05-01', null, 'Preparar apresentação em grupo sobre células-tronco', 'PENDENTE', 4, 5);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Apresentação de trabalho em congresso', '2023-05-25', '2023-05-22', 'Levar pôster e preparar apresentação oral', 'ENTREGUE', 5, 18);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Resenha de livro de literatura', '2023-06-01', null, 'Livro "Dom Casmurro" de Machado de Assis', 'PENDENTE', 3, 10);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Exercícios de programação em Java', '2023-06-10', null, 'Do livro "Java - Como Programar"', 'PENDENTE', 1, 25);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparação para aula de física', '2023-06-15', null, 'Leitura do capítulo 7 do livro didático', 'PENDENTE', 2, 45);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Elaboração de roteiro de teatro', '2023-07-01', null, 'Para apresentação na Semana Cultural', 'PENDENTE', 6, 22);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Leitura de artigo científico', '2023-07-15', null, 'Artigo sobre inteligência artificial', 'PENDENTE', 3, 38);

INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Fazer exercícios de cálculo', '2023-04-05', null, 'Capítulo 4', 'PENDENTE', 1, 10);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de história', '2023-04-15', null, null, 'PENDENTE', 2, 23);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Pesquisa sobre teoria literária', '2023-04-25', null, 'Orientação do professor', 'PENDENTE', 3, 15);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho em grupo de sociologia', '2023-04-20', null, 'Elaboração do projeto', 'PENDENTE', 4, 5);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Participar de congresso de psicologia', '2023-05-03', '2023-04-30', null, 'ENTREGUE', 5, 30);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Preparar apresentação de seminário', '2023-04-27', null, 'Tópicos selecionados', 'PENDENTE', 6, 8);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Fazer exercícios de física', '2023-04-10', null, 'Capítulo 5', 'PENDENTE', 1, 42);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Estudar para prova de biologia', '2023-04-18', null, null, 'PENDENTE', 2, 17);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Pesquisa sobre filosofia moderna', '2023-04-23', null, 'Referências bibliográficas', 'PENDENTE', 3, 21);
INSERT INTO tarefa (descricao, data_Final_Da_Entrega, data_Entrega, observacao, tipo, codigo_categoria, codigo_usuario) VALUES ('Trabalho em grupo de literatura', '2023-04-30', null, 'Divisão de tarefas', 'PENDENTE', 4, 3);